# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: mycomputeragent

stages:
  - stage: BuildApp
    jobs:
    - job: BuildPushImage
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'my docker'
          repository: 'milanster/test'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: '$(Build.BuildId)'
  
  - stage: DeployDev
    jobs:
      - deployment: deploy
        environment: myenv
        strategy:
         runOnce:
           deploy:
             steps:
               - script: echo HELLO WORLD